name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.10", "3.13"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v6

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v4.0.1
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: build

      - name: Install native dependencies
        run: bash .github/scripts/install-native-deps.sh

      - name: Prepare
        run: conda install -y conda-build conda-verify pytest

      - name: Build
        env:
          CMAKE_PREFIX_PATH: /usr/local
        run: conda-build conda.recipe

      - name: Install
        run: conda install -y -c local vda5050

      - name: Test
        run: pytest tests
